### ISSUE TITLE
Kitex Nacos 无法支持通过配置文件的方式进行注册

### ISSUE THREAD

**Issue by HowardLei** [kitex-contrib/registry-nacos#11]
**Is your feature request related to a problem? Please describe.**
现在的 Kitex 中的 nacos 注册的时候只能通过修改本地启动命令来设置命令。

**Describe the solution you'd like**
想通过配置文件的方式配置注册中心的相关属性

**Describe alternatives you've considered**
设计 appplication.properties 文件，并根据对应的键值对加载相关参数

**Additional context**
无

**Comment by baiyutang** [comment]
我的理解是这样：registry-nacos 只是一个组件，不是一个应用，不应该过重。
可以在应用服务中读取相应配置，然后初始化注册中心的配置。
你觉得呢？

**Comment by li-jin-gou** [comment]
https://github.com/kitex-contrib/registry-nacos/pull/12 自定义配置可以参考 @HowardLei

**Comment by GuangmingLuo** [comment]
有需要的话，可以自行结合 golang 生态的配置库进行适配，如 viper，可读取 json，toml，ini，yaml，hcl，env 等格式的文件内容

**Comment by HowardLei** [comment]
> #12 自定义配置可以参考 @HowardLei

好的，感谢
