### ISSUE TITLE
关于获取本地ip的问题

### ISSUE THREAD

**Issue by sjy-sujianyu** [kitex-contrib/registry-nacos#17]
getLocalIpv4Host()函数不能获取公网ip，只能获取内网的。

**Comment by baiyutang** [comment]
> getLocalIpv4Host()函数不能获取公网ip，只能获取内网的。

了解下什么情况下会用到公网？
可以更具体的描述下你的背景和要解决的问题，说不定不是这个问题或者换一个思路。
常规来说一组微服务更多时候在同一个内网。并且一般很少直接暴露在公网环境，比如很多时候会前置一个 LB 或者业务网关等等。

**Comment by sjy-sujianyu** [comment]
我是在测试微服务的时候发现了这一个问题，如果是生产环境确实只需要注册内网地址就好了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月15日(周三) 下午4:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kitex-contrib/registry-nacos] 关于获取本地ip的问题 (Issue #17)




  
getLocalIpv4Host()函数不能获取公网ip，只能获取内网的。
  
了解下什么情况下会用到公网？
 常规来说一组微服务更多时候在同一个内网。并且一般很少直接暴露在公网环境，比如很多时候会前置一个 LB 或者业务网关等等。

**Comment by baiyutang** [comment]
So? 那这里是符合预期的。还有别的疑问嘛？

**Comment by sjy-sujianyu** [comment]
没有了，谢谢哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月16日(周四) 上午9:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kitex-contrib/registry-nacos] 关于获取本地ip的问题 (Issue #17)




 
So? 那这里是符合预期的。还有别的疑问嘛？
