### ISSUE TITLE
支持nacos2.0

### ISSUE THREAD

**Issue by LordHarrt** [kitex-contrib/registry-nacos#22]
目前nacos contrib无法支持nacos2.0

**Comment by GuangmingLuo** [comment]
This Package use Nacos1.x client. The Nacos2.0 and Nacos1.0 Server are fully compatible with it. [see](https://nacos.io/en-us/docs/v2/upgrading/2.0.0-compatibility.html)

**Comment by GuangmingLuo** [comment]
refer: https://github.com/kitex-contrib/registry-nacos/issues/21
