### ISSUE TITLE
取消监听的执行顺序可能会导致 panic

### ISSUE THREAD

**Issue by ViolaPioggia** [kitex-contrib/registry-nacos#24]
**Describe the bug**
如果先关闭了 cbSuite，还没来得及关闭监听，这时正好有一个配置变更，cb 为 nil，就会 panic

client 的另外两个配置可能也有类似的问题

**Comment by ViolaPioggia** [comment]
<img width="673" alt="QQ20231106-143111@2x" src="https://github.com/kitex-contrib/registry-nacos/assets/114391708/e24cad93-7832-448d-8d4f-fa0908e06f9a">

**Comment by baiyutang** [comment]
配置中心问题，请移步：https://github.com/kitex-contrib/config-nacos
